/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wbsedcl.trms.kafka.substation.log.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EnergyConsumptionAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4388979717035327915L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnergyConsumptionAvroModel\",\"namespace\":\"com.wbsedcl.trms.kafka.substation.log.avro.model\",\"fields\":[{\"name\":\"energyConsumptionId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"feederId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"substationOfficeId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"recordedBy\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"date\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"time\",\"type\":{\"type\":\"long\",\"logicalType\":\"time-millis\"}},{\"name\":\"energyMeterNo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"energyUnit\",\"type\":{\"type\":\"enum\",\"name\":\"EnergyUnit\",\"symbols\":[\"WH\",\"KWH\",\"MWH\"]}},{\"name\":\"consumption\",\"type\":\"double\"},{\"name\":\"multiplyingFactor\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<EnergyConsumptionAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EnergyConsumptionAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EnergyConsumptionAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EnergyConsumptionAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EnergyConsumptionAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EnergyConsumptionAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EnergyConsumptionAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EnergyConsumptionAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EnergyConsumptionAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID energyConsumptionId;
  private java.util.UUID sagaId;
  private java.lang.String feederId;
  private java.lang.String substationOfficeId;
  private java.lang.String recordedBy;
  private java.time.LocalDate date;
  private long time;
  private java.lang.String energyMeterNo;
  private com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit energyUnit;
  private double consumption;
  private int multiplyingFactor;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EnergyConsumptionAvroModel() {}

  /**
   * All-args constructor.
   * @param energyConsumptionId The new value for energyConsumptionId
   * @param sagaId The new value for sagaId
   * @param feederId The new value for feederId
   * @param substationOfficeId The new value for substationOfficeId
   * @param recordedBy The new value for recordedBy
   * @param date The new value for date
   * @param time The new value for time
   * @param energyMeterNo The new value for energyMeterNo
   * @param energyUnit The new value for energyUnit
   * @param consumption The new value for consumption
   * @param multiplyingFactor The new value for multiplyingFactor
   */
  public EnergyConsumptionAvroModel(java.util.UUID energyConsumptionId, java.util.UUID sagaId, java.lang.String feederId, java.lang.String substationOfficeId, java.lang.String recordedBy, java.time.LocalDate date, java.lang.Long time, java.lang.String energyMeterNo, com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit energyUnit, java.lang.Double consumption, java.lang.Integer multiplyingFactor) {
    this.energyConsumptionId = energyConsumptionId;
    this.sagaId = sagaId;
    this.feederId = feederId;
    this.substationOfficeId = substationOfficeId;
    this.recordedBy = recordedBy;
    this.date = date;
    this.time = time;
    this.energyMeterNo = energyMeterNo;
    this.energyUnit = energyUnit;
    this.consumption = consumption;
    this.multiplyingFactor = multiplyingFactor;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return energyConsumptionId;
    case 1: return sagaId;
    case 2: return feederId;
    case 3: return substationOfficeId;
    case 4: return recordedBy;
    case 5: return date;
    case 6: return time;
    case 7: return energyMeterNo;
    case 8: return energyUnit;
    case 9: return consumption;
    case 10: return multiplyingFactor;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.DateConversion(),
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: energyConsumptionId = (java.util.UUID)value$; break;
    case 1: sagaId = (java.util.UUID)value$; break;
    case 2: feederId = value$ != null ? value$.toString() : null; break;
    case 3: substationOfficeId = value$ != null ? value$.toString() : null; break;
    case 4: recordedBy = value$ != null ? value$.toString() : null; break;
    case 5: date = (java.time.LocalDate)value$; break;
    case 6: time = (java.lang.Long)value$; break;
    case 7: energyMeterNo = value$ != null ? value$.toString() : null; break;
    case 8: energyUnit = (com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit)value$; break;
    case 9: consumption = (java.lang.Double)value$; break;
    case 10: multiplyingFactor = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'energyConsumptionId' field.
   * @return The value of the 'energyConsumptionId' field.
   */
  public java.util.UUID getEnergyConsumptionId() {
    return energyConsumptionId;
  }


  /**
   * Sets the value of the 'energyConsumptionId' field.
   * @param value the value to set.
   */
  public void setEnergyConsumptionId(java.util.UUID value) {
    this.energyConsumptionId = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.util.UUID getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.util.UUID value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'feederId' field.
   * @return The value of the 'feederId' field.
   */
  public java.lang.String getFeederId() {
    return feederId;
  }


  /**
   * Sets the value of the 'feederId' field.
   * @param value the value to set.
   */
  public void setFeederId(java.lang.String value) {
    this.feederId = value;
  }

  /**
   * Gets the value of the 'substationOfficeId' field.
   * @return The value of the 'substationOfficeId' field.
   */
  public java.lang.String getSubstationOfficeId() {
    return substationOfficeId;
  }


  /**
   * Sets the value of the 'substationOfficeId' field.
   * @param value the value to set.
   */
  public void setSubstationOfficeId(java.lang.String value) {
    this.substationOfficeId = value;
  }

  /**
   * Gets the value of the 'recordedBy' field.
   * @return The value of the 'recordedBy' field.
   */
  public java.lang.String getRecordedBy() {
    return recordedBy;
  }


  /**
   * Sets the value of the 'recordedBy' field.
   * @param value the value to set.
   */
  public void setRecordedBy(java.lang.String value) {
    this.recordedBy = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.time.LocalDate getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.time.LocalDate value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public long getTime() {
    return time;
  }


  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(long value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'energyMeterNo' field.
   * @return The value of the 'energyMeterNo' field.
   */
  public java.lang.String getEnergyMeterNo() {
    return energyMeterNo;
  }


  /**
   * Sets the value of the 'energyMeterNo' field.
   * @param value the value to set.
   */
  public void setEnergyMeterNo(java.lang.String value) {
    this.energyMeterNo = value;
  }

  /**
   * Gets the value of the 'energyUnit' field.
   * @return The value of the 'energyUnit' field.
   */
  public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit getEnergyUnit() {
    return energyUnit;
  }


  /**
   * Sets the value of the 'energyUnit' field.
   * @param value the value to set.
   */
  public void setEnergyUnit(com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit value) {
    this.energyUnit = value;
  }

  /**
   * Gets the value of the 'consumption' field.
   * @return The value of the 'consumption' field.
   */
  public double getConsumption() {
    return consumption;
  }


  /**
   * Sets the value of the 'consumption' field.
   * @param value the value to set.
   */
  public void setConsumption(double value) {
    this.consumption = value;
  }

  /**
   * Gets the value of the 'multiplyingFactor' field.
   * @return The value of the 'multiplyingFactor' field.
   */
  public int getMultiplyingFactor() {
    return multiplyingFactor;
  }


  /**
   * Sets the value of the 'multiplyingFactor' field.
   * @param value the value to set.
   */
  public void setMultiplyingFactor(int value) {
    this.multiplyingFactor = value;
  }

  /**
   * Creates a new EnergyConsumptionAvroModel RecordBuilder.
   * @return A new EnergyConsumptionAvroModel RecordBuilder
   */
  public static com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder newBuilder() {
    return new com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder();
  }

  /**
   * Creates a new EnergyConsumptionAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EnergyConsumptionAvroModel RecordBuilder
   */
  public static com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder newBuilder(com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder other) {
    if (other == null) {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder();
    } else {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new EnergyConsumptionAvroModel RecordBuilder by copying an existing EnergyConsumptionAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new EnergyConsumptionAvroModel RecordBuilder
   */
  public static com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder newBuilder(com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel other) {
    if (other == null) {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder();
    } else {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for EnergyConsumptionAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnergyConsumptionAvroModel>
    implements org.apache.avro.data.RecordBuilder<EnergyConsumptionAvroModel> {

    private java.util.UUID energyConsumptionId;
    private java.util.UUID sagaId;
    private java.lang.String feederId;
    private java.lang.String substationOfficeId;
    private java.lang.String recordedBy;
    private java.time.LocalDate date;
    private long time;
    private java.lang.String energyMeterNo;
    private com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit energyUnit;
    private double consumption;
    private int multiplyingFactor;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.energyConsumptionId)) {
        this.energyConsumptionId = data().deepCopy(fields()[0].schema(), other.energyConsumptionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.feederId)) {
        this.feederId = data().deepCopy(fields()[2].schema(), other.feederId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.substationOfficeId)) {
        this.substationOfficeId = data().deepCopy(fields()[3].schema(), other.substationOfficeId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.recordedBy)) {
        this.recordedBy = data().deepCopy(fields()[4].schema(), other.recordedBy);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.date)) {
        this.date = data().deepCopy(fields()[5].schema(), other.date);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.time)) {
        this.time = data().deepCopy(fields()[6].schema(), other.time);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.energyMeterNo)) {
        this.energyMeterNo = data().deepCopy(fields()[7].schema(), other.energyMeterNo);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.energyUnit)) {
        this.energyUnit = data().deepCopy(fields()[8].schema(), other.energyUnit);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.consumption)) {
        this.consumption = data().deepCopy(fields()[9].schema(), other.consumption);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.multiplyingFactor)) {
        this.multiplyingFactor = data().deepCopy(fields()[10].schema(), other.multiplyingFactor);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing EnergyConsumptionAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.energyConsumptionId)) {
        this.energyConsumptionId = data().deepCopy(fields()[0].schema(), other.energyConsumptionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.feederId)) {
        this.feederId = data().deepCopy(fields()[2].schema(), other.feederId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.substationOfficeId)) {
        this.substationOfficeId = data().deepCopy(fields()[3].schema(), other.substationOfficeId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.recordedBy)) {
        this.recordedBy = data().deepCopy(fields()[4].schema(), other.recordedBy);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.date)) {
        this.date = data().deepCopy(fields()[5].schema(), other.date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.time)) {
        this.time = data().deepCopy(fields()[6].schema(), other.time);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.energyMeterNo)) {
        this.energyMeterNo = data().deepCopy(fields()[7].schema(), other.energyMeterNo);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.energyUnit)) {
        this.energyUnit = data().deepCopy(fields()[8].schema(), other.energyUnit);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.consumption)) {
        this.consumption = data().deepCopy(fields()[9].schema(), other.consumption);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.multiplyingFactor)) {
        this.multiplyingFactor = data().deepCopy(fields()[10].schema(), other.multiplyingFactor);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'energyConsumptionId' field.
      * @return The value.
      */
    public java.util.UUID getEnergyConsumptionId() {
      return energyConsumptionId;
    }


    /**
      * Sets the value of the 'energyConsumptionId' field.
      * @param value The value of 'energyConsumptionId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setEnergyConsumptionId(java.util.UUID value) {
      validate(fields()[0], value);
      this.energyConsumptionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'energyConsumptionId' field has been set.
      * @return True if the 'energyConsumptionId' field has been set, false otherwise.
      */
    public boolean hasEnergyConsumptionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'energyConsumptionId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearEnergyConsumptionId() {
      energyConsumptionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.util.UUID getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setSagaId(java.util.UUID value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'feederId' field.
      * @return The value.
      */
    public java.lang.String getFeederId() {
      return feederId;
    }


    /**
      * Sets the value of the 'feederId' field.
      * @param value The value of 'feederId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setFeederId(java.lang.String value) {
      validate(fields()[2], value);
      this.feederId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'feederId' field has been set.
      * @return True if the 'feederId' field has been set, false otherwise.
      */
    public boolean hasFeederId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'feederId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearFeederId() {
      feederId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'substationOfficeId' field.
      * @return The value.
      */
    public java.lang.String getSubstationOfficeId() {
      return substationOfficeId;
    }


    /**
      * Sets the value of the 'substationOfficeId' field.
      * @param value The value of 'substationOfficeId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setSubstationOfficeId(java.lang.String value) {
      validate(fields()[3], value);
      this.substationOfficeId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'substationOfficeId' field has been set.
      * @return True if the 'substationOfficeId' field has been set, false otherwise.
      */
    public boolean hasSubstationOfficeId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'substationOfficeId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearSubstationOfficeId() {
      substationOfficeId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'recordedBy' field.
      * @return The value.
      */
    public java.lang.String getRecordedBy() {
      return recordedBy;
    }


    /**
      * Sets the value of the 'recordedBy' field.
      * @param value The value of 'recordedBy'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setRecordedBy(java.lang.String value) {
      validate(fields()[4], value);
      this.recordedBy = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'recordedBy' field has been set.
      * @return True if the 'recordedBy' field has been set, false otherwise.
      */
    public boolean hasRecordedBy() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'recordedBy' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearRecordedBy() {
      recordedBy = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.time.LocalDate getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setDate(java.time.LocalDate value) {
      validate(fields()[5], value);
      this.date = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearDate() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public long getTime() {
      return time;
    }


    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setTime(long value) {
      validate(fields()[6], value);
      this.time = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearTime() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'energyMeterNo' field.
      * @return The value.
      */
    public java.lang.String getEnergyMeterNo() {
      return energyMeterNo;
    }


    /**
      * Sets the value of the 'energyMeterNo' field.
      * @param value The value of 'energyMeterNo'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setEnergyMeterNo(java.lang.String value) {
      validate(fields()[7], value);
      this.energyMeterNo = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'energyMeterNo' field has been set.
      * @return True if the 'energyMeterNo' field has been set, false otherwise.
      */
    public boolean hasEnergyMeterNo() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'energyMeterNo' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearEnergyMeterNo() {
      energyMeterNo = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'energyUnit' field.
      * @return The value.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit getEnergyUnit() {
      return energyUnit;
    }


    /**
      * Sets the value of the 'energyUnit' field.
      * @param value The value of 'energyUnit'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setEnergyUnit(com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit value) {
      validate(fields()[8], value);
      this.energyUnit = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'energyUnit' field has been set.
      * @return True if the 'energyUnit' field has been set, false otherwise.
      */
    public boolean hasEnergyUnit() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'energyUnit' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearEnergyUnit() {
      energyUnit = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'consumption' field.
      * @return The value.
      */
    public double getConsumption() {
      return consumption;
    }


    /**
      * Sets the value of the 'consumption' field.
      * @param value The value of 'consumption'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setConsumption(double value) {
      validate(fields()[9], value);
      this.consumption = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'consumption' field has been set.
      * @return True if the 'consumption' field has been set, false otherwise.
      */
    public boolean hasConsumption() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'consumption' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearConsumption() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'multiplyingFactor' field.
      * @return The value.
      */
    public int getMultiplyingFactor() {
      return multiplyingFactor;
    }


    /**
      * Sets the value of the 'multiplyingFactor' field.
      * @param value The value of 'multiplyingFactor'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder setMultiplyingFactor(int value) {
      validate(fields()[10], value);
      this.multiplyingFactor = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'multiplyingFactor' field has been set.
      * @return True if the 'multiplyingFactor' field has been set, false otherwise.
      */
    public boolean hasMultiplyingFactor() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'multiplyingFactor' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyConsumptionAvroModel.Builder clearMultiplyingFactor() {
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EnergyConsumptionAvroModel build() {
      try {
        EnergyConsumptionAvroModel record = new EnergyConsumptionAvroModel();
        record.energyConsumptionId = fieldSetFlags()[0] ? this.energyConsumptionId : (java.util.UUID) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.util.UUID) defaultValue(fields()[1]);
        record.feederId = fieldSetFlags()[2] ? this.feederId : (java.lang.String) defaultValue(fields()[2]);
        record.substationOfficeId = fieldSetFlags()[3] ? this.substationOfficeId : (java.lang.String) defaultValue(fields()[3]);
        record.recordedBy = fieldSetFlags()[4] ? this.recordedBy : (java.lang.String) defaultValue(fields()[4]);
        record.date = fieldSetFlags()[5] ? this.date : (java.time.LocalDate) defaultValue(fields()[5]);
        record.time = fieldSetFlags()[6] ? this.time : (java.lang.Long) defaultValue(fields()[6]);
        record.energyMeterNo = fieldSetFlags()[7] ? this.energyMeterNo : (java.lang.String) defaultValue(fields()[7]);
        record.energyUnit = fieldSetFlags()[8] ? this.energyUnit : (com.wbsedcl.trms.kafka.substation.log.avro.model.EnergyUnit) defaultValue(fields()[8]);
        record.consumption = fieldSetFlags()[9] ? this.consumption : (java.lang.Double) defaultValue(fields()[9]);
        record.multiplyingFactor = fieldSetFlags()[10] ? this.multiplyingFactor : (java.lang.Integer) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EnergyConsumptionAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<EnergyConsumptionAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EnergyConsumptionAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<EnergyConsumptionAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










