/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wbsedcl.trms.kafka.substation.log.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum FaultNature implements org.apache.avro.generic.GenericEnumSymbol<FaultNature> {
  EF_OC, EF, OC, HIGH_SET_OC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FaultNature\",\"namespace\":\"com.wbsedcl.trms.kafka.substation.log.avro.model\",\"symbols\":[\"EF_OC\",\"EF\",\"OC\",\"HIGH_SET_OC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
