/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wbsedcl.trms.kafka.substation.log.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum FeederType implements org.apache.avro.generic.GenericEnumSymbol<FeederType> {
  INCOMING_33kV, OUTGOING_33kV, PTR_BAY, OUTGOING_11kV, INCOMING_11kV  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FeederType\",\"namespace\":\"com.wbsedcl.trms.kafka.substation.log.avro.model\",\"symbols\":[\"INCOMING_33kV\",\"OUTGOING_33kV\",\"PTR_BAY\",\"OUTGOING_11kV\",\"INCOMING_11kV\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
