/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wbsedcl.trms.kafka.substation.log.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum InterruptionType implements org.apache.avro.generic.GenericEnumSymbol<InterruptionType> {
  TRANSIENT_TRIPPING, MAIN_POWER_FAIL, LOAD_SHEDDING, PLANNED_SHUTDOWN, EMERGENCY_SHUTDOWN, SUSTAINED_FAULT, SOURCE_CHANGEOVER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InterruptionType\",\"namespace\":\"com.wbsedcl.trms.kafka.substation.log.avro.model\",\"symbols\":[\"TRANSIENT_TRIPPING\",\"MAIN_POWER_FAIL\",\"LOAD_SHEDDING\",\"PLANNED_SHUTDOWN\",\"EMERGENCY_SHUTDOWN\",\"SUSTAINED_FAULT\",\"SOURCE_CHANGEOVER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
