/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wbsedcl.trms.kafka.substation.log.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum InterruptionStatus implements org.apache.avro.generic.GenericEnumSymbol<InterruptionStatus> {
  NOT_RESTORED, RESTORED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InterruptionStatus\",\"namespace\":\"com.wbsedcl.trms.kafka.substation.log.avro.model\",\"symbols\":[\"NOT_RESTORED\",\"RESTORED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
