/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wbsedcl.trms.kafka.substation.log.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RestoredInterruptionAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3830021031606173238L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RestoredInterruptionAvroModel\",\"namespace\":\"com.wbsedcl.trms.kafka.substation.log.avro.model\",\"fields\":[{\"name\":\"interruptionId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"faultyFeederId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"substationOfficeId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"restoredBy\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cause\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"endDate\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"endTime\",\"type\":{\"type\":\"long\",\"logicalType\":\"time-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<RestoredInterruptionAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RestoredInterruptionAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RestoredInterruptionAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RestoredInterruptionAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RestoredInterruptionAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RestoredInterruptionAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RestoredInterruptionAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RestoredInterruptionAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RestoredInterruptionAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID interruptionId;
  private java.util.UUID sagaId;
  private java.lang.String faultyFeederId;
  private java.lang.String substationOfficeId;
  private java.lang.String restoredBy;
  private java.lang.String cause;
  private java.time.LocalDate endDate;
  private long endTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RestoredInterruptionAvroModel() {}

  /**
   * All-args constructor.
   * @param interruptionId The new value for interruptionId
   * @param sagaId The new value for sagaId
   * @param faultyFeederId The new value for faultyFeederId
   * @param substationOfficeId The new value for substationOfficeId
   * @param restoredBy The new value for restoredBy
   * @param cause The new value for cause
   * @param endDate The new value for endDate
   * @param endTime The new value for endTime
   */
  public RestoredInterruptionAvroModel(java.util.UUID interruptionId, java.util.UUID sagaId, java.lang.String faultyFeederId, java.lang.String substationOfficeId, java.lang.String restoredBy, java.lang.String cause, java.time.LocalDate endDate, java.lang.Long endTime) {
    this.interruptionId = interruptionId;
    this.sagaId = sagaId;
    this.faultyFeederId = faultyFeederId;
    this.substationOfficeId = substationOfficeId;
    this.restoredBy = restoredBy;
    this.cause = cause;
    this.endDate = endDate;
    this.endTime = endTime;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return interruptionId;
    case 1: return sagaId;
    case 2: return faultyFeederId;
    case 3: return substationOfficeId;
    case 4: return restoredBy;
    case 5: return cause;
    case 6: return endDate;
    case 7: return endTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.DateConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: interruptionId = (java.util.UUID)value$; break;
    case 1: sagaId = (java.util.UUID)value$; break;
    case 2: faultyFeederId = value$ != null ? value$.toString() : null; break;
    case 3: substationOfficeId = value$ != null ? value$.toString() : null; break;
    case 4: restoredBy = value$ != null ? value$.toString() : null; break;
    case 5: cause = value$ != null ? value$.toString() : null; break;
    case 6: endDate = (java.time.LocalDate)value$; break;
    case 7: endTime = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'interruptionId' field.
   * @return The value of the 'interruptionId' field.
   */
  public java.util.UUID getInterruptionId() {
    return interruptionId;
  }


  /**
   * Sets the value of the 'interruptionId' field.
   * @param value the value to set.
   */
  public void setInterruptionId(java.util.UUID value) {
    this.interruptionId = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.util.UUID getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.util.UUID value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'faultyFeederId' field.
   * @return The value of the 'faultyFeederId' field.
   */
  public java.lang.String getFaultyFeederId() {
    return faultyFeederId;
  }


  /**
   * Sets the value of the 'faultyFeederId' field.
   * @param value the value to set.
   */
  public void setFaultyFeederId(java.lang.String value) {
    this.faultyFeederId = value;
  }

  /**
   * Gets the value of the 'substationOfficeId' field.
   * @return The value of the 'substationOfficeId' field.
   */
  public java.lang.String getSubstationOfficeId() {
    return substationOfficeId;
  }


  /**
   * Sets the value of the 'substationOfficeId' field.
   * @param value the value to set.
   */
  public void setSubstationOfficeId(java.lang.String value) {
    this.substationOfficeId = value;
  }

  /**
   * Gets the value of the 'restoredBy' field.
   * @return The value of the 'restoredBy' field.
   */
  public java.lang.String getRestoredBy() {
    return restoredBy;
  }


  /**
   * Sets the value of the 'restoredBy' field.
   * @param value the value to set.
   */
  public void setRestoredBy(java.lang.String value) {
    this.restoredBy = value;
  }

  /**
   * Gets the value of the 'cause' field.
   * @return The value of the 'cause' field.
   */
  public java.lang.String getCause() {
    return cause;
  }


  /**
   * Sets the value of the 'cause' field.
   * @param value the value to set.
   */
  public void setCause(java.lang.String value) {
    this.cause = value;
  }

  /**
   * Gets the value of the 'endDate' field.
   * @return The value of the 'endDate' field.
   */
  public java.time.LocalDate getEndDate() {
    return endDate;
  }


  /**
   * Sets the value of the 'endDate' field.
   * @param value the value to set.
   */
  public void setEndDate(java.time.LocalDate value) {
    this.endDate = value;
  }

  /**
   * Gets the value of the 'endTime' field.
   * @return The value of the 'endTime' field.
   */
  public long getEndTime() {
    return endTime;
  }


  /**
   * Sets the value of the 'endTime' field.
   * @param value the value to set.
   */
  public void setEndTime(long value) {
    this.endTime = value;
  }

  /**
   * Creates a new RestoredInterruptionAvroModel RecordBuilder.
   * @return A new RestoredInterruptionAvroModel RecordBuilder
   */
  public static com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder newBuilder() {
    return new com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder();
  }

  /**
   * Creates a new RestoredInterruptionAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RestoredInterruptionAvroModel RecordBuilder
   */
  public static com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder newBuilder(com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder other) {
    if (other == null) {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder();
    } else {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new RestoredInterruptionAvroModel RecordBuilder by copying an existing RestoredInterruptionAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new RestoredInterruptionAvroModel RecordBuilder
   */
  public static com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder newBuilder(com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel other) {
    if (other == null) {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder();
    } else {
      return new com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for RestoredInterruptionAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RestoredInterruptionAvroModel>
    implements org.apache.avro.data.RecordBuilder<RestoredInterruptionAvroModel> {

    private java.util.UUID interruptionId;
    private java.util.UUID sagaId;
    private java.lang.String faultyFeederId;
    private java.lang.String substationOfficeId;
    private java.lang.String restoredBy;
    private java.lang.String cause;
    private java.time.LocalDate endDate;
    private long endTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.interruptionId)) {
        this.interruptionId = data().deepCopy(fields()[0].schema(), other.interruptionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.faultyFeederId)) {
        this.faultyFeederId = data().deepCopy(fields()[2].schema(), other.faultyFeederId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.substationOfficeId)) {
        this.substationOfficeId = data().deepCopy(fields()[3].schema(), other.substationOfficeId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.restoredBy)) {
        this.restoredBy = data().deepCopy(fields()[4].schema(), other.restoredBy);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.cause)) {
        this.cause = data().deepCopy(fields()[5].schema(), other.cause);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.endDate)) {
        this.endDate = data().deepCopy(fields()[6].schema(), other.endDate);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.endTime)) {
        this.endTime = data().deepCopy(fields()[7].schema(), other.endTime);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing RestoredInterruptionAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.interruptionId)) {
        this.interruptionId = data().deepCopy(fields()[0].schema(), other.interruptionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.faultyFeederId)) {
        this.faultyFeederId = data().deepCopy(fields()[2].schema(), other.faultyFeederId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.substationOfficeId)) {
        this.substationOfficeId = data().deepCopy(fields()[3].schema(), other.substationOfficeId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.restoredBy)) {
        this.restoredBy = data().deepCopy(fields()[4].schema(), other.restoredBy);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cause)) {
        this.cause = data().deepCopy(fields()[5].schema(), other.cause);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.endDate)) {
        this.endDate = data().deepCopy(fields()[6].schema(), other.endDate);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.endTime)) {
        this.endTime = data().deepCopy(fields()[7].schema(), other.endTime);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'interruptionId' field.
      * @return The value.
      */
    public java.util.UUID getInterruptionId() {
      return interruptionId;
    }


    /**
      * Sets the value of the 'interruptionId' field.
      * @param value The value of 'interruptionId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setInterruptionId(java.util.UUID value) {
      validate(fields()[0], value);
      this.interruptionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'interruptionId' field has been set.
      * @return True if the 'interruptionId' field has been set, false otherwise.
      */
    public boolean hasInterruptionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'interruptionId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearInterruptionId() {
      interruptionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.util.UUID getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setSagaId(java.util.UUID value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'faultyFeederId' field.
      * @return The value.
      */
    public java.lang.String getFaultyFeederId() {
      return faultyFeederId;
    }


    /**
      * Sets the value of the 'faultyFeederId' field.
      * @param value The value of 'faultyFeederId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setFaultyFeederId(java.lang.String value) {
      validate(fields()[2], value);
      this.faultyFeederId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'faultyFeederId' field has been set.
      * @return True if the 'faultyFeederId' field has been set, false otherwise.
      */
    public boolean hasFaultyFeederId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'faultyFeederId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearFaultyFeederId() {
      faultyFeederId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'substationOfficeId' field.
      * @return The value.
      */
    public java.lang.String getSubstationOfficeId() {
      return substationOfficeId;
    }


    /**
      * Sets the value of the 'substationOfficeId' field.
      * @param value The value of 'substationOfficeId'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setSubstationOfficeId(java.lang.String value) {
      validate(fields()[3], value);
      this.substationOfficeId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'substationOfficeId' field has been set.
      * @return True if the 'substationOfficeId' field has been set, false otherwise.
      */
    public boolean hasSubstationOfficeId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'substationOfficeId' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearSubstationOfficeId() {
      substationOfficeId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'restoredBy' field.
      * @return The value.
      */
    public java.lang.String getRestoredBy() {
      return restoredBy;
    }


    /**
      * Sets the value of the 'restoredBy' field.
      * @param value The value of 'restoredBy'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setRestoredBy(java.lang.String value) {
      validate(fields()[4], value);
      this.restoredBy = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'restoredBy' field has been set.
      * @return True if the 'restoredBy' field has been set, false otherwise.
      */
    public boolean hasRestoredBy() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'restoredBy' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearRestoredBy() {
      restoredBy = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'cause' field.
      * @return The value.
      */
    public java.lang.String getCause() {
      return cause;
    }


    /**
      * Sets the value of the 'cause' field.
      * @param value The value of 'cause'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setCause(java.lang.String value) {
      validate(fields()[5], value);
      this.cause = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'cause' field has been set.
      * @return True if the 'cause' field has been set, false otherwise.
      */
    public boolean hasCause() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'cause' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearCause() {
      cause = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'endDate' field.
      * @return The value.
      */
    public java.time.LocalDate getEndDate() {
      return endDate;
    }


    /**
      * Sets the value of the 'endDate' field.
      * @param value The value of 'endDate'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setEndDate(java.time.LocalDate value) {
      validate(fields()[6], value);
      this.endDate = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'endDate' field has been set.
      * @return True if the 'endDate' field has been set, false otherwise.
      */
    public boolean hasEndDate() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'endDate' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearEndDate() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'endTime' field.
      * @return The value.
      */
    public long getEndTime() {
      return endTime;
    }


    /**
      * Sets the value of the 'endTime' field.
      * @param value The value of 'endTime'.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder setEndTime(long value) {
      validate(fields()[7], value);
      this.endTime = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'endTime' field has been set.
      * @return True if the 'endTime' field has been set, false otherwise.
      */
    public boolean hasEndTime() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'endTime' field.
      * @return This builder.
      */
    public com.wbsedcl.trms.kafka.substation.log.avro.model.RestoredInterruptionAvroModel.Builder clearEndTime() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RestoredInterruptionAvroModel build() {
      try {
        RestoredInterruptionAvroModel record = new RestoredInterruptionAvroModel();
        record.interruptionId = fieldSetFlags()[0] ? this.interruptionId : (java.util.UUID) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.util.UUID) defaultValue(fields()[1]);
        record.faultyFeederId = fieldSetFlags()[2] ? this.faultyFeederId : (java.lang.String) defaultValue(fields()[2]);
        record.substationOfficeId = fieldSetFlags()[3] ? this.substationOfficeId : (java.lang.String) defaultValue(fields()[3]);
        record.restoredBy = fieldSetFlags()[4] ? this.restoredBy : (java.lang.String) defaultValue(fields()[4]);
        record.cause = fieldSetFlags()[5] ? this.cause : (java.lang.String) defaultValue(fields()[5]);
        record.endDate = fieldSetFlags()[6] ? this.endDate : (java.time.LocalDate) defaultValue(fields()[6]);
        record.endTime = fieldSetFlags()[7] ? this.endTime : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RestoredInterruptionAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<RestoredInterruptionAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RestoredInterruptionAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<RestoredInterruptionAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










