server:
  port: 8181

logging:
  level:
    com.wbsedcl.trms: DEBUG
    org.apache.kafka.clients.NetworkClient: OFF
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.session: DEBUG
    org.springframework.session.data.redis: DEBUG
  file:
    path: /
    name: logs.txt

spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        ddl-auto: create
        ddl-auto: create-drop
  redis:
    port: 8081
    host: localhost
  session:
    store-type: redis


  datasource:
#    url: jdbc:mysql://sublog-database.c5myc0qgexo6.ap-south-1.rds.amazonaws.com:3306/substation_log_schema
    url: jdbc:mysql://localhost:3306/substation_log_schema
    username: springstudent
#    username: admin
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations:
        - classpath:init-schema.sql
      data-locations:
        - classpath:init-data.sql
      mode: always


kafka-config:
#  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  bootstrap-servers: localhost:19092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#define consumer group ids here
  feeder-service-consumer-group-id: created-feeder-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150
  specific-avro-reader: true

substation-log-service:
  logged-interruption-topic-name: logged-interruptions
  restored-interruption-topic-name: restored-interruptions
  logged-energy-consumption-topic-name: logged-energy-consumptions
  logged-load-record-topic-name: logged-load-records
  created-feeder-topic-name: created-feeders
